name: dart_intensity_map
description: An absolute bare-bones web app.
version: 1.0.0
repository: https://github.com/YumNumm/dart_intensity_map

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  riverpod: ^2.3.6
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.0
  custom_lint: ^0.4.0
  lints: ^2.0.0
  pedantic_mono: ^1.23.0
  riverpod_generator: ^2.2.4
  riverpod_lint: ^1.4.0
